---
version: 2
jobs:
  build:
    working_directory: ~/everybodysquat
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: everybodysquat
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: everybodysquat
          POSTGRES_DB: everybodysquat_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: everybodysquat-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: everybodysquat-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      # - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec

      # - deploy:
      #     command: bundle exec rake build:deploy

      - run: bundle exec rake build:deploy
      

# # Ruby CircleCI 2.0 configuration file
# #
# # Check https://circleci.com/docs/2.0/language-ruby/ for more details
# #
# version: 2
# jobs:
#   build:
#     docker:
#        - image: circleci/ruby:2.6.3-node-browsers
#          environment:
#             RAILS_ENV: test
#             PGHOST: 127.0.0.1
#             PGUSER: root

#       # Specify service dependencies here if necessary
#       # CircleCI maintains a library of pre-built images
#       # documented at https://circleci.com/docs/2.0/circleci-images/
#        - image: circleci/postgres:9.5-alpine
#          environment:
#             POSTGRES_USER: root
#             POSTGRES_DB: everybodysquat_test

#     # working_directory: ~/repo

#     steps:
#       - checkout

#       # Download and cache dependencies
#       - restore_cache:
#           keys:
#           - v1-dependencies-{{ checksum "Gemfile.lock" }}
#           # fallback to using the latest cache if no exact match is found
#           - v1-dependencies-

#       - run:
#           name: install dependencies
#           command: |
#             bundle install --jobs=4 --retry=3 --path vendor/bundle

#       - save_cache:
#           paths:
#             - ./vendor/bundle
#           key: v1-dependencies-{{ checksum "Gemfile.lock" }}

#       # Database setup
#       - run: bundle exec rake db:create
#       - run: bundle exec rake db:schema:load

#       # run tests!
#       - run:
#           name: run tests
#           command: |
#             mkdir /tmp/test-results
#             TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"

#             bundle exec rspec --format progress \
#                             --format RspecJunitFormatter \
#                             --out /tmp/test-results/rspec.xml \
#                             --format progress \
#                             $TEST_FILES
#       # collect reports
#       - store_test_results:
#           path: /tmp/test-results
#       - store_artifacts:
#           path: /tmp/test-results
#           destination: test-results

#       # - deploy:
#       #     command: ./.circleci/deploy.sh

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build